### ISSUE TITLE
multiplatform

### ISSUE THREAD

**Issue by vmaark** [Dolers/MagusBuddy-release#1]
Not sure what technologies are used to build the app (why not open source?), it should be a fairly straightforward `react-native` application if the data is already available. I can offer some help if needed.

**Comment by Dolers** [comment]
Hi,

I'm currently don't consider making the project to open source. Maybe sometime later.
I think I keep my fair distance from front-end frameworks, simply because you need a certain amount of trust, that the magic glue works.
